### ISSUE TITLE
Terraform Not Taking in Command Options

### ISSUE THREAD

**Issue by liamfoneill** [microsoft/azure-pipelines-extensions#685] opened 2019-09-04 14:47 UTC
On the 'validate and apply' task I am trying to pass an additional argument to set my variables file to be a specific file, but when I run it, I don't see the additional arguments being passed in from the Azure DevOps logs. I see just 'terraform.exe validate' being run.

**Comment by RoshanKumarMicrosoft** [comment] 2019-09-06 09:47
@liamfoneill  Can you please share your debug log to RM_Customer_Queries@microsoft.com ?

**Comment by RoshanKumarMicrosoft** [comment] 2019-10-07 06:40
@liamfoneill Not able to reproduce on our end So I am closing this issue. If you still face any issue please ping us on RM_Customer_Queries@microsoft.com.

**Closed by RoshanKumarMicrosoft** 2019-10-07 06:40 UTC
Labels: Area: Release
