### ISSUE TITLE
Download Build Artifacts-Proxy issue(status =Failed in getBuild with error: Error: tunneling socket could not be established, cause=socket hang up)

### ISSUE THREAD

**Issue by solkeee** [Microsoft/azure-pipelines-extensions#596] opened 2019-02-24 22:20 UTC
Hi @omeshp we have the agent under proxy using integrated windows/ntlm authentication.
The deployment group shows the resource as connected and the status is shown as green.
However when we run the release we are seeing the following error :
Failed in getBuild with error: Error: tunneling socket could not be established, cause=socket hang up tunneling socket could not be established, cause=socket hang up

Logs:
2019-02-23T05:28:14.2007043Z ##[section]Starting: Download artifact - - drop
2019-02-23T05:28:14.2288585Z ==============================================================================
2019-02-23T05:28:14.2288746Z Task : Download Build Artifacts
2019-02-23T05:28:14.2288814Z Description : Download Build Artifacts
2019-02-23T05:28:14.2288856Z Version : 0.146.0
2019-02-23T05:28:14.2288900Z Author : Microsoft Corporation
2019-02-23T05:28:14.2288942Z Help :
2019-02-23T05:28:14.2289735Z ==============================================================================
2019-02-23T05:28:15.2394372Z Error: in getBuild, so retrying => retries pending : 4
2019-02-23T05:28:19.2779695Z Error: in getBuild, so retrying => retries pending : 3
2019-02-23T05:28:23.3143664Z Error: in getBuild, so retrying => retries pending : 2
2019-02-23T05:28:27.3450235Z Error: in getBuild, so retrying => retries pending : 1
2019-02-23T05:28:31.3784490Z ##[error]Failed in getBuild with error: Error: tunneling socket could not be established, cause=socket hang up
2019-02-23T05:28:31.4203301Z ##[error]Error: tunneling socket could not be established, cause=socket hang up
2019-02-23T05:28:31.4281709Z ##[section]Finishing: Download artifact - - drop

Any help will be appriciated,

Thanks

**Comment by omeshp** [comment] 2019-02-27 12:55
Closing the issue since it was confirmed to be resolved on other thread. @solkeee Please reopen if you are still facing the issue.

**Closed by omeshp** 2019-02-27 12:55 UTC
