### ISSUE TITLE
Publishing build artifacts failed with an error

### ISSUE THREAD

**Issue by sorgeas** [microsoft/azure-pipelines-extensions#559] opened 2018-12-20 13:30 UTC
Hello,

After setting up a new build agent for TFS 2018, we encounter the following issue when trying to publish an artifact:

```
2018-12-20T12:44:04.6871664Z ##[error]Publishing build artifacts failed with an error: powershell.exe failed. spawn powershell.exe ENOENT
2018-12-20T12:44:04.6884095Z ##[debug]Processed: ##vso[task.issue type=error;]Publishing build artifacts failed with an error: powershell.exe failed. spawn powershell.exe ENOENT
2018-12-20T12:44:04.6885503Z ##[debug]Processed: ##vso[task.complete result=Failed;]Publishing build artifacts failed with an error: powershell.exe failed. spawn powershell.exe ENOENT
```

The build steps are the following : MSBuild, Archive Files, Copy and Publish Build Artifacts
Here is the agent version: 2.133.3
And the publish task version: 1.131.0

Please note that this new agent has been setup on a machine containing another agent from a different agent pool. Could you please help us resolving this issue?

Thanks for your help!

**Comment by omeshp** [comment] 2019-02-27 13:02
@sorgeas This repo is for extensions, if the issue is with 'publish build artifacts' task please report it at https://github.com/Microsoft/azure-pipelines-tasks

**Comment by omeshp** [comment] 2019-05-09 10:02
@sorgeas Closing this issue please look the issue at https://github.com/Microsoft/azure-pipelines-tasks for traction

**Closed by omeshp** 2019-05-09 10:02 UTC
Labels: Area: Release
