### ISSUE TITLE
Update Terraform task 

### ISSUE THREAD

**Issue by liamfoneill** [microsoft/azure-pipelines-extensions#738] opened 2019-12-02 16:37 UTC
Terraform Task is using deprecated backend config input parameters. Please update them.

Terraform Task Version: 0.0.137
Terraform Version: 0.12.16
Azure Provider Version: 1.37.0

`2019-12-02T16:17:08.0597927Z Initializing the backend...
2019-12-02T16:17:08.1348103Z 
2019-12-02T16:17:08.1349587Z Successfully configured the backend "azurerm"! Terraform will automatically
2019-12-02T16:17:08.1349978Z use this backend unless the backend configuration changes.
2019-12-02T16:17:08.5835303Z 
2019-12-02T16:17:08.5838278Z Warning: "arm_tenant_id": [DEPRECATED] `arm_tenant_id` has been replaced by `tenant_id`
2019-12-02T16:17:08.5838427Z 
2019-12-02T16:17:08.5838521Z 
2019-12-02T16:17:08.5838559Z 
2019-12-02T16:17:08.5838639Z Warning: "arm_subscription_id": [DEPRECATED] `arm_subscription_id` has been replaced by `subscription_id`
2019-12-02T16:17:08.5838753Z 
2019-12-02T16:17:08.5838789Z 
2019-12-02T16:17:08.5838827Z 
2019-12-02T16:17:08.5838946Z Warning: "arm_client_id": [DEPRECATED] `arm_client_id` has been replaced by `client_id`
2019-12-02T16:17:08.5839017Z 
2019-12-02T16:17:08.5839051Z 
2019-12-02T16:17:08.5839086Z 
2019-12-02T16:17:08.5839211Z Warning: "arm_client_secret": [DEPRECATED] `arm_client_secret` has been replaced by `client_secret`
2019-12-02T16:17:08.5839277Z 
2019-12-02T16:17:08.5839362Z 
2019-12-02T16:17:08.5839398Z `

![image](https://user-images.githubusercontent.com/1243172/69977136-2316f580-1522-11ea-95a2-5d9722b2a410.png)

**Comment by Roshan-Kumar-Microsoft** [comment] 2020-01-03 08:38
@liamfoneill Due to other priority work we are not picking this for now. We are open for contribution. You can create PR and assign to me.

**Closed by Roshan-Kumar-Microsoft** 2020-01-03 08:38 UTC
Labels: Area: Release

**Comment by NK74** [comment] 2020-09-15 17:41
Hi,
still not fixed

**Comment by copjon** [comment] 2020-11-11 16:54
Any movement on approving #863? It would be nice to stop getting deprecation warnings in my builds 😅

**Comment by AmrutaKawade** [comment] 2020-11-12 07:36
duplicate of https://github.com/microsoft/azure-pipelines-extensions/issues/882
