### ISSUE TITLE
Backend Config items deprecated

### ISSUE THREAD

**Issue by nrmatukumalli** [microsoft/azure-pipelines-extensions#786] opened 2020-03-09 03:39 UTC
# Terraform Backend configuration

Following codebase need to update the back configuration. 
`azure-pipelines-extensions/Extensions/Terraform/Src/Tasks/TerraformTaskV1/src/azure-terraform-command-handler.ts`

currently arm_* prefix is used in the backend configuration which are deprecated in terraform resulting in a warning messages. 

```
this.backendConfig.set('arm_subscription_id', tasks.getEndpointDataParameter(backendServiceName, "subscriptionid", true));
this.backendConfig.set('arm_tenant_id', tasks.getEndpointAuthorizationParameter(backendServiceName, "tenantid", true));
this.backendConfig.set('arm_client_id', tasks.getEndpointAuthorizationParameter(backendServiceName, "serviceprincipalid", true));
this.backendConfig.set('arm_client_secret', tasks.getEndpointAuthorizationParameter(backendServiceName, "serviceprincipalkey", true));
```

**Comment by AmrutaKawade** [comment] 2020-11-12 07:35
duplicate of https://github.com/microsoft/azure-pipelines-extensions/issues/882 closing this issue

**Closed by AmrutaKawade** 2020-11-12 07:35 UTC
Labels: Terraform:enhancement, enhancement
