### ISSUE TITLE
Task: Download Build Artifacts - Proxy issue (statusCode=407)

### ISSUE THREAD

**Issue by Kloe2257** [Microsoft/azure-pipelines-extensions#341] opened 2017-12-19 13:36 UTC
# Environment

VSTS 
From the output:
        [AGENT_VERSION] --> [2.123.0]
        [AGENT_OS] --> [Windows_NT]
        [AGENT_PROXYURL] --> [http://.....]
	[AGENT_PROXYUSERNAME] --> [.....]

# Issue Description

Since last VSTS update (monday 18 dec.), we now see 2 download artifact tasks in our releases.

The first, named "Download Artifacts", goes **well** (but seems to do nothing):
```
2017-12-19T11:27:03.5785813Z ##[section]Starting: Download Artifacts
2017-12-19T11:27:03.9217769Z Downloading artifact
2017-12-19T11:27:03.9217769Z Creating artifacts directory: C:\Users\<...>\Documents\vstsAgent\_work\r6\a
2017-12-19T11:27:03.9373767Z Created artifacts directory: C:\Users\<...>\Documents\vstsAgent\_work\r6\a
2017-12-19T11:27:03.9373767Z Finished artifacts download
2017-12-19T11:27:03.9373767Z Downloading commits
2017-12-19T11:27:03.9373767Z ##[section]Finishing: Download Artifacts
```

The (new) second, named "Download artifact - ..project name..", goes **wrong**:
```
2017-12-19T11:27:03.9373767Z ##[section]Starting: Download artifact - <project name>
2017-12-19T11:27:03.9529765Z ==============================================================================
2017-12-19T11:27:03.9529765Z Task         : Download Build Artifacts
2017-12-19T11:27:03.9529765Z Description  : Download Build Artifacts
2017-12-19T11:27:03.9529765Z Version      : 0.127.5
2017-12-19T11:27:03.9529765Z Author       : Microsoft Corporation
2017-12-19T11:27:03.9529765Z Help         : 
2017-12-19T11:27:03.9529765Z ==============================================================================
2017-12-19T11:27:04.6549675Z Error : in getBuild, so retrying => retries pending  : 4
2017-12-19T11:27:08.6173167Z Error : in getBuild, so retrying => retries pending  : 3
2017-12-19T11:27:12.6264653Z Error : in getBuild, so retrying => retries pending  : 2
2017-12-19T11:27:16.6356139Z Error : in getBuild, so retrying => retries pending  : 1
2017-12-19T11:27:20.6447625Z ##[error]Failed in getBuild with error: Error: tunneling socket could not be established, statusCode=407
2017-12-19T11:27:21.3467535Z ##[error]Error: tunneling socket could not be established, statusCode=407
2017-12-19T11:27:21.3467535Z ##[section]Async Command Start: Telemetry
2017-12-19T11:27:21.3779531Z ##[section]Async Command End: Telemetry
2017-12-19T11:27:21.3779531Z ##[section]Finishing: Download artifact - <project name>
```

We tried any proxy configuration detailed in the doc (.proxy, env variables, config.cmd, etc.) with no luck:
https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/proxy?tabs=windows

It was working fine before the last update, but all our releases are totally stuck since monday (the last successful release run on 2017-12-18T11:40:46.0673787Z, all failed afterwards without any changes on our side).
Any ideas on the proxy config we should set to pass this new download artifact task ?

**Comment by omeshp** [comment] 2017-12-19 14:22
@Kloe2257 What is you vsts-account name?

**Comment by Kloe2257** [comment] 2017-12-19 14:34
Hello, i work on airbus-caddmu.visualstudio.com.

**Comment by omeshp** [comment] 2017-12-19 14:40
ok, i have disable the feature of downloading artifact using tasks for your account till we investigate why proxy isn't working for you.

**Comment by Kloe2257** [comment] 2017-12-19 14:59
Ok thank you! 
I am not able to access the "Build and Release" tab anymore on the website (503 Service unavailable).
But an admin on the team still have access and the release went well again.

```
Additional technical details:
Activity ID: 6d5f3c20-6f39-4769-925a-9ef1124047a2 
Date and Time: 19/12/2017 14:56:43 (UTC) 
```

**Comment by omeshp** [comment] 2017-12-19 15:58
@Kloe2257 I was able to repro this issue locally, it looks like getBuild api call fails if proxy password has \ in it. Can you confirm if your proxy password is also using this character?

**Comment by Kloe2257** [comment] 2017-12-19 16:11
We have a "\" in the user name due to the domain prefix, and a ":" in the password.

**Comment by omeshp** [comment] 2017-12-20 11:33
https://github.com/Microsoft/typed-rest-client/pull/50

**Comment by Kloe2257** [comment] 2017-12-20 17:47
Thank you for fixing this.
Should we re-enable the feature of downloading artifact using tasks on my account ?

**Comment by omeshp** [comment] 2017-12-21 08:42
@Kloe2257 The issue isn't fixed yet, the issue is in typed-rest-client that is getting used in vso-node-api. Those issues still need to be fixed. Once they have been fixed and deployed, I will enabled the feature for your account and update you.

**Comment by Schindler-VSTS-Group** [comment] 2018-01-18 10:48
Hi,
We are also affected with the same issue above. Can you disable the feature for artifacts download, for our tenant as well ?
We are behind an Enterprise proxy with NTLM authentication and all our deployments are stuck due to the new version. 
Thank you in advance for treating this issue with a high emergency.

**Comment by GitHubSriramB** [comment] 2018-01-18 11:50
@Schindler-VSTS-Group - could you pl. let us know your account name?

**Comment by Schindler-VSTS-Group** [comment] 2018-01-18 12:02
Hi , It is nazmunnisa.ghani@schindler.com.

**Comment by Schindler-VSTS-Group** [comment] 2018-01-18 12:06
Hi It is nazmunnisa.ghani@schindler.com @GitHubSriramB

**Comment by omeshp** [comment] 2018-01-18 14:20
@Schindler-VSTS-Group I had seen failures for your account from telemetry and disabled the feature some time back, are you still facing this issue?

**Comment by Schindler-VSTS-Group** [comment] 2018-01-18 14:27
Unfortunately i still see the same issue . 
![2018-01-18_15-25-08](https://user-images.githubusercontent.com/35562230/35102751-c1bf81a2-fc5b-11e7-9fd3-0107fdc36bf3.png)

**Comment by omeshp** [comment] 2018-01-18 14:29
@Schindler-VSTS-Group Are you redeploying the same release, or creating a new one?

**Comment by Schindler-VSTS-Group** [comment] 2018-01-18 14:46
Hey cool. It worked fine with the new release. Thanks very Much!.

**Comment by Schindler-VSTS-Group** [comment] 2018-01-18 14:52
Hope it will be fixed in next release and please let me know if i need to request back again to enable the feature not to miss out the functionalities provided...

**Comment by omeshp** [comment] 2018-01-18 15:31
@Schindler-VSTS-Group Yes, we are working on support for NTLM once we have thoroughly tested and deployed the fix, we will re-enable the feature for your account. We will keep you updated when we do that.

**Comment by harrywaters-swordmobile** [comment] 2018-02-08 13:14
HI @omeshp - we are seeing the same issue, it was working yesterday but is not working today in VSTS

`2018-02-08T13:12:02.0189245Z ==============================================================================
2018-02-08T13:12:02.0189470Z Task         : Download Build Artifacts
2018-02-08T13:12:02.0189687Z Description  : Download Build Artifacts
2018-02-08T13:12:02.0189841Z Version      : 0.129.1
2018-02-08T13:12:02.0190030Z Author       : Microsoft Corporation
2018-02-08T13:12:02.0190180Z Help         : 
2018-02-08T13:12:02.0190349Z ==============================================================================
2018-02-08T13:12:03.3660216Z Error : in getBuild, so retrying => retries pending  : 4
2018-02-08T13:12:06.4872443Z Error : in getBuild, so retrying => retries pending  : 3
2018-02-08T13:12:10.4986233Z Error : in getBuild, so retrying => retries pending  : 2
2018-02-08T13:12:14.5039271Z Error : in getBuild, so retrying => retries pending  : 1
2018-02-08T13:12:18.5247876Z ##[error]Failed in getBuild with error: Error: tunneling socket could not be established, statusCode=407
2018-02-08T13:12:19.1433046Z ##[error]Error: tunneling socket could not be established, statusCode=407`

**Comment by GitHubSriramB** [comment] 2018-02-09 06:01
@harrywaters-swordmobile - We have seen this issue happen when agent is configured to use proxy with NTLM credentials. Can you check if this is the case with the agent where the release failed?

**Comment by harrywaters-swordmobile** [comment] 2018-02-09 08:41
Hi @GitHubSriramB - yes I believe this is the case, is there anything we can do about it?

**Comment by GitHubSriramB** [comment] 2018-02-09 08:50
@harrywaters-swordmobile - is it possible to not use agent behind proxy configured with NTLM credentials? 

If this is not possible, then we would need to turn off feature for your account. Pl. share the account name where you are running into this issue.

**Comment by harrywaters-swordmobile** [comment] 2018-02-09 08:59
What feature are you referring to? The task was working with version:

`2018-02-07T17:18:00.4109601Z ==============================================================================
2018-02-07T17:18:00.4109869Z Task         : Download Build Artifacts
2018-02-07T17:18:00.4110030Z Description  : Download Build Artifacts
2018-02-07T17:18:00.4110200Z Version      : 0.127.7
2018-02-07T17:18:00.4110354Z Author       : Microsoft Corporation
2018-02-07T17:18:00.4110511Z Help         : 
2018-02-07T17:18:00.4110681Z ==============================================================================`

And is now not working with version:

`2018-02-08T12:04:26.5673887Z ==============================================================================
2018-02-08T12:04:26.5674128Z Task         : Download Build Artifacts
2018-02-08T12:04:26.5674345Z Description  : Download Build Artifacts
2018-02-08T12:04:26.5674503Z Version      : 0.129.1
2018-02-08T12:04:26.5674696Z Author       : Microsoft Corporation
2018-02-08T12:04:26.5674850Z Help         : 
2018-02-08T12:04:26.5675015Z ==============================================================================`

**Comment by harrywaters-swordmobile** [comment] 2018-02-09 09:33
@GitHubSriramB - apologies I forgot to tell you our account, it is swordmobile.visualstudio.com

**Comment by GitHubSriramB** [comment] 2018-02-22 13:03
@harrywaters-swordmobile - we have disabled feature to use DownloadBuildArtifacts task automatically to download artifacts used in release.

**Comment by ntiesotrade** [comment] 2018-07-25 14:15
We are experiencing this same issue.  Does the agent still not work behind a proxy that requires NTLM credentials?

**Comment by omeshp** [comment] 2018-08-22 07:00
@tradearchitect Yes, NTLM proxy is still an issue with node based tasks, you can use using http://cntlm.sourceforge.net/ is no other proxy authentication is supported. Or let us know and we can turn of this feature for your account if it is really blocking you. 

Also, better to open a new thread for the issue since we don't monitor closed ones.

**Comment by c-patil** [comment] 2018-11-30 19:32
Is this issue resolved? We are also facing same issue. Our release agent is running behind proxy and it's blocking Download Artifacts task.

**Comment by omeshp** [comment] 2018-12-03 07:49
@c-patil Is you proxy using integrated windows auth for authentication? what is your account name?

**Comment by omeshp** [comment] 2019-01-23 05:03
@omerzubair Is your agent under proxy? Is the proxy using integrated windows/NTLM authentication?

**Comment by solkeee** [comment] 2019-02-23 05:57
Hi @omeshp we have the agent under proxy using integrated windows/ntlm authentication.
The deployment group shows the resource as connected and the status is shown as green.
However when we run the release we are seeing the following error :
Failed in getBuild with error: Error: tunneling socket could not be established, cause=socket hang up tunneling socket could not be established, cause=socket hang up

**Comment by solkeee** [comment] 2019-02-23 06:07
@omeshp additional information:
2019-02-23T05:28:14.2007043Z ##[section]Starting: Download artifact - <ProjectName> - drop
2019-02-23T05:28:14.2288585Z ==============================================================================
2019-02-23T05:28:14.2288746Z Task         : Download Build Artifacts
2019-02-23T05:28:14.2288814Z Description  : Download Build Artifacts
2019-02-23T05:28:14.2288856Z Version      : 0.146.0
2019-02-23T05:28:14.2288900Z Author       : Microsoft Corporation
2019-02-23T05:28:14.2288942Z Help         : 
2019-02-23T05:28:14.2289735Z ==============================================================================
2019-02-23T05:28:15.2394372Z Error: in getBuild, so retrying => retries pending  : 4
2019-02-23T05:28:19.2779695Z Error: in getBuild, so retrying => retries pending  : 3
2019-02-23T05:28:23.3143664Z Error: in getBuild, so retrying => retries pending  : 2
2019-02-23T05:28:27.3450235Z Error: in getBuild, so retrying => retries pending  : 1
2019-02-23T05:28:31.3784490Z ##[error]Failed in getBuild with error: Error: tunneling socket could not be established, cause=socket hang up
2019-02-23T05:28:31.4203301Z ##[error]Error: tunneling socket could not be established, cause=socket hang up
2019-02-23T05:28:31.4281709Z ##[section]Finishing: Download artifact - <ProjectName> - drop

**Comment by omeshp** [comment] 2019-02-25 06:19
@solkeee Can you provide your account details?

**Comment by solkeee** [comment] 2019-02-25 10:43
@omeshp account : dev.azure.com/lloydslondon

**Comment by omeshp** [comment] 2019-02-25 12:35
ok, i have switched your account to use agent based download flow, can you try now?

**Comment by solkeee** [comment] 2019-02-25 12:51
I have re-triggered the release and its failed with the same results :
2019-02-25T12:49:42.7439033Z ##[section]Starting: Download artifact - _SysMon-CI - drop
2019-02-25T12:49:42.7665573Z ==============================================================================
2019-02-25T12:49:42.7665712Z Task         : Download Build Artifacts
2019-02-25T12:49:42.7665868Z Description  : Download Build Artifacts
2019-02-25T12:49:42.7665912Z Version      : 0.146.0
2019-02-25T12:49:42.7665954Z Author       : Microsoft Corporation
2019-02-25T12:49:42.7665995Z Help         : 
2019-02-25T12:49:42.7666055Z ==============================================================================
2019-02-25T12:49:43.3682294Z Error: in getBuild, so retrying => retries pending  : 4
2019-02-25T12:49:47.4062078Z Error: in getBuild, so retrying => retries pending  : 3
2019-02-25T12:49:51.4350368Z Error: in getBuild, so retrying => retries pending  : 2
2019-02-25T12:49:55.4624645Z Error: in getBuild, so retrying => retries pending  : 1
2019-02-25T12:49:59.4981456Z ##[error]Failed in getBuild with error: Error: tunneling socket could not be established, cause=socket hang up
2019-02-25T12:49:59.5361281Z ##[error]Error: tunneling socket could not be established, cause=socket hang up
2019-02-25T12:49:59.5424253Z ##[section]Finishing: Download artifact - _SysMon-CI - drop

**Comment by omeshp** [comment] 2019-02-25 14:03
@solkeee Can you try creating a new release instead of re-triggering the old one?

-

**Comment by solkeee** [comment] 2019-02-25 14:12
@omeshp Thanks re-triggering the new release has worked for us.

**Closed** 2019-02-27 12:54 UTC

**Comment by YuliiaBabychKdd** [comment] 2019-04-19 13:19
Ah i got same issue. 
2019-04-19T13:17:50.0499914Z ##[section]Starting: Download artifact - dev-sync-CI - drop
2019-04-19T13:17:50.2134891Z ==============================================================================
2019-04-19T13:17:50.2135122Z Task         : Download Build Artifacts
2019-04-19T13:17:50.2135660Z Description  : Download Build Artifacts
2019-04-19T13:17:50.2135750Z Version      : 0.148.1
2019-04-19T13:17:50.2135805Z Author       : Microsoft Corporation
2019-04-19T13:17:50.2135861Z Help         : 
2019-04-19T13:17:50.2135933Z ==============================================================================
2019-04-19T13:17:55.9940756Z Error: in getBuild, so retrying => retries pending  : 4
2019-04-19T13:17:56.2544875Z Error: in getBuild, so retrying => retries pending  : 3
2019-04-19T13:18:00.2619227Z Error: in getBuild, so retrying => retries pending  : 2
2019-04-19T13:18:04.2646649Z Error: in getBuild, so retrying => retries pending  : 1
2019-04-19T13:18:08.2806378Z ##[error]Failed in getBuild with error: Error: tunneling socket could not be established, statusCode=407
2019-04-19T13:18:08.3456974Z ##[error]Error: tunneling socket could not be established, statusCode=407
2019-04-19T13:18:08.3527737Z ##[section]Finishing: Download artifact - dev-sync-CI - drop

**Comment by omeshp** [comment] 2019-04-22 05:50
Hi @YuliiaBabychKdd, 'Download build artifacts' doesn't work well with some proxy setups. Is it possible for you to use [Pipeline Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml) instead? (You can use [Publish pipeline artifacts](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishPipelineArtifactV0) and [Download pipeline artifacts](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/DownloadPipelineArtifactV1) for pipeline artifacts.)

**Comment by YuliiaBabychKdd** [comment] 2019-04-23 12:39
was trying to use another pipeline, but now got same error on nuget restore task (one of task build agent)

##[section]Starting: Use NuGet 
==============================================================================
Task         : NuGet Tool Installer
Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
Version      : 1.150.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=852538)
==============================================================================
You are using a query match on the version string. Behavior changes or breaking changes might occur as NuGet updates to a new version.
ERR:tunneling socket could not be established, statusCode=407
##[section]Finishing: Use NuGet

**Comment by omeshp** [comment] 2019-04-23 12:57
Hi @YuliiaBabychKdd can you create a new issue for nuget related error, it will help to get traction for the issue from relevant team.

**Comment by Mike032** [comment] 2019-05-02 14:06
@omeshp We are having the same issue. 

2019-05-02T13:34:21.1550838Z Error: in getBuild, so retrying => retries pending  : 4
2019-05-02T13:34:24.8927730Z Error: in getBuild, so retrying => retries pending  : 3
2019-05-02T13:34:28.9006281Z Error: in getBuild, so retrying => retries pending  : 2
2019-05-02T13:34:32.9170046Z Error: in getBuild, so retrying => retries pending  : 1
2019-05-02T13:34:36.9509703Z ##[error]Failed in getBuild with error: Error: tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:

2019-05-02T13:34:36.9524406Z ##[debug]Processed: ##vso[task.issue type=error;]Failed in getBuild with error: Error: tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:%0A

Accountname: https://dev.azure.com/gs-projects

**Comment by omeshp** [comment] 2019-05-03 05:53
@Mike032 There are know issue with proxy in "Download Build Artifacts". Can you start using "Publish pipeline artifacts" and "Download Pipeline Artifacts" tasks instead?

**Comment by Mike032** [comment] 2019-05-07 07:36
@omeshp This indeed works. 
Thanks for your help.
