### ISSUE TITLE
Add arm_environment as backend-config options to terraform init to enable non-public Azure cloud

### ISSUE THREAD

**Issue by VincentLyu** [microsoft/azure-pipelines-extensions#674] opened 2019-08-19 16:49 UTC
Terraform need cloud environment(usgovernment, german, china) to autofill those special PaaS URL like storage account, but currently we can't set it as backend-config options:

2019-08-19T16:30:41.7809973Z ##[section]Starting: Terraform : init
2019-08-19T16:30:41.7926846Z ==============================================================================
2019-08-19T16:30:41.7926945Z Task         : Terraform
2019-08-19T16:30:41.7927046Z Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
2019-08-19T16:30:41.7927127Z Version      : 0.0.137
2019-08-19T16:30:41.7927192Z Author       : Microsoft Corporation
2019-08-19T16:30:41.7927285Z Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
2019-08-19T16:30:41.7927366Z ==============================================================================
2019-08-19T16:30:42.0685131Z [command]C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe init **-backend-config=arm_environment=china** "-backend-config=storage_account_name=$( terraformstorageaccount)" -backend-config=container_name=terraform -backend-config=key=terraform.tfstate -backend-config=resource_group_name=terraformrg -backend-config=arm_subscription_id=6d1964e4-c7cc-4ef0-ba2b-c15c69bdfb4e -backend-config=arm_tenant_id=*** -backend-config=arm_client_id=*** -backend-config=arm_client_secret=***
2019-08-19T16:30:42.2251136Z 
2019-08-19T16:30:42.2262489Z ‌
2019-08-19T16:30:42.2263118Z ‌**Error: ‌Invalid backend configuration argument‌**
2019-08-19T16:30:42.2264291Z 
2019-08-19T16:30:42.2264598Z ‌The backend configuration argument &quot;arm_environment&quot; given on the command line‌
2019-08-19T16:30:42.2264805Z is not expected for the selected backend type.
2019-08-19T16:30:42.2264966Z ‌Initializing the backend...‌
2019-08-19T16:30:42.2268052Z ‌
2019-08-19T16:30:42.2732598Z ##[error]Error: The process 'C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe' failed with exit code 1
2019-08-19T16:30:42.2744113Z ##[section]Finishing: Terraform : init

Could you add one more options, pls? Thanks.

**Comment by RoshanKumarMicrosoft** [comment] 2019-09-18 07:45
@VincentLyu current time it is not supported but we will add this in next release. We are also open for contribution you can also create PR and assign to me.

**Comment by RoshanKumarMicrosoft** [comment] 2019-09-18 09:56
Created PR .. 
@VincentLyu  Can you please try with this changes ? We had already verified this.
How to upload this task 
You can either use cmd or powershell to run the commands.

1. Clone the vsts tasks repo ( git clone https://github.com/Microsoft/azure-pipelines-extensions ).
2. checkout to users/rok/cloud-url-terraform branch
3. cd into this repo.
4. run: npm install
5. run: npm install -g tfx-cli
6. run: gulp build --task TerraformTaskV1
7. run: tfx login
   ( the url provided should be: 
     'https://roshansampleproject.visualstudio.com/DefaultCollection' . The command will also prompt you for a PAT, which you will need to generate from the security tab in TFS)
8. run: tfx build tasks upload --task-path .\_build\Tasks\TerraformTaskV1 
9. The task should now be uploaded and you should see it as part of the task dropdown.
10. run: tfx logout

**Comment by VincentLyu** [comment] 2019-09-20 09:37
sorry, got some access error when gulp build task, even i change the read-only attribute to the dir:

_build\Extensions\ArtifactEngine\Providers\stubProvider.ts(42,11): error TS2445: Property '_read' is protected and only accessible within class 'Readable' and its subclasses.
_build\Extensions\CopyStageVariableToReleaseVariable\Src\Tasks\CopyAgentJobVariableToReleaseVariable\copyvartorelease.ts(42,101): error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.
_build\Extensions\CopyStageVariableToReleaseVariable\Src\Tasks\CopyAgentJobVariableToReleaseVariable\copyvartorelease.ts(60,93): error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.
C:/Terraform/azure-pipelines-extensions/_build/Extensions/CopyStageVariableToReleaseVariable/Src/Tasks/CopyAgentJobVariableToReleaseVariable/node_modules/azure-devops-node-api/ReleaseApi.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
C:/Terraform/azure-pipelines-extensions/_build/Extensions/CopyStageVariableToReleaseVariable/Src/Tasks/CopyAgentJobVariableToReleaseVariable/node_modules/azure-devops-node-api/ReleaseApi.d.ts(94,40): error TS1039: Initializers are not allowed in ambient contexts.
C:/Terraform/azure-pipelines-extensions/_build/Extensions/CopyStageVariableToReleaseVariable/Src/Tasks/CopyAgentJobVariableToReleaseVariable/node_modules/azure-devops-node-api/interfaces/common/VsoBaseInterfaces.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
C:/Terraform/azure-pipelines-extensions/_build/Extensions/CopyStageVariableToReleaseVariable/Src/Tasks/CopyAgentJobVariableToReleaseVariable/node_modules/typed-rest-client/HttpClient.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
C:/Terraform/azure-pipelines-extensions/_build/Extensions/CopyStageVariableToReleaseVariable/Src/Tasks/CopyAgentJobVariableToReleaseVariable/node_modules/typed-rest-client/Interfaces.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
C:/Terraform/azure-pipelines-extensions/_build/Extensions/CopyStageVariableToReleaseVariable/Src/Tasks/CopyAgentJobVariableToReleaseVariable/node_modules/typed-rest-client/RestClient.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.

**Comment by RoshanKumarMicrosoft** [comment] 2019-10-04 10:24
@VincentLyu can you please share your skypeId. So we can help you to upload this task in your account.  Please share your skypeId on RM_Customer_Queries@microsoft.com.

**Comment by VincentLyu** [comment] 2019-10-09 08:53
My skypeid is welv@microsoft.com. Thanks.

Cheers,
Vincent

**Comment by AmrutaKawade** [comment] 2020-09-21 08:14
@VincentLyu this is old issue and wanted to check whether you found the resolution or not?

**Comment by AmrutaKawade** [comment] 2020-11-10 10:43
Duplicate of https://github.com/microsoft/azure-pipelines-extensions/issues/868 closing this. will track will other issue

**Closed by AmrutaKawade** 2020-11-10 10:43 UTC
Labels: Area: Release, Terraform:enhancement, enhancement
