### ISSUE TITLE
Node 6 to node 10 - Warnings Terraform tasks 

### ISSUE THREAD

**Issue by alexMagicBeans** [microsoft/azure-pipelines-extensions#1001] opened 2021-11-17 11:04 UTC
Hello, Any updates regarding the warnings that are showing in every terraform task ?

I'm using Microsoft-hosted agents and every terraform tasks from the MicrosftDevLabs are getting this warning:

##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

Is there any date to solve this warnings? Or any fix?

thanks!

**Comment by alexMagicBeans** [comment] 2021-11-17 11:09
Actually, it also happens in other tasks, like the CopyFiles@2 task;

**Comment by mericstam** [comment] 2021-11-17 12:14
duplicate of issue #1000

**Comment by devopsenggineer** [comment] 2021-11-22 15:11
Any update when these new changes get updated so that this https://github.com/microsoft/azure-pipelines-extensions/issues/1001  issue gets resolved?

**Closed** 2021-11-22 16:08 UTC
Labels: Extension: Terraform
